#ifndef COMMON_H
#define COMMON_H

#define SCREEN_HEIGHT 600
#define SCREEN_WIDTH 800
#define MAX_WORLD_COLS 50
#define MAX_WORLD_ROWS 50
#define WORLD_HEIGHT 1600
#define WORLD_WIDTH 1600
#define PLAYERS_COUNT 1

#endif